# Generated by Django 4.0 on 2021-12-11 19:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('boards', '0001_initial'), ('boards', '0002_boardsettings_remove_trelloboard_desc_and_more'), ('boards', '0003_alter_boardsettings_trello_api_key_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrelloBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trello_id', models.CharField(max_length=24, unique=True)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrelloList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trello_id', models.CharField(max_length=24, unique=True)),
                ('name', models.TextField()),
                ('tboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.trelloboard', to_field='trello_id')),
            ],
        ),
        migrations.CreateModel(
            name='TrelloCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trello_id', models.CharField(max_length=24, unique=True)),
                ('name', models.TextField()),
                ('position', models.FloatField()),
                ('tlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.trellolist', to_field='trello_id')),
            ],
        ),
        migrations.CreateModel(
            name='BoardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('trello_api_token', models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(64)])),
                ('trello_api_key', models.CharField(max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(32)])),
                ('trello_board_name', models.TextField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
