# Generated by Django 4.0 on 2021-12-11 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrelloBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trello_id', models.CharField(max_length=24, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='TrelloList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trello_id', models.CharField(max_length=24, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField(verbose_name='description')),
                ('tboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.trelloboard', to_field='trello_id')),
            ],
        ),
        migrations.CreateModel(
            name='TrelloCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trello_id', models.CharField(max_length=24, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField(verbose_name='description')),
                ('position', models.FloatField()),
                ('tlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.trellolist', to_field='trello_id')),
            ],
        ),
    ]
