version: '3.8'

services:
  trello-app:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - ./app/.env.dev
  trello-db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=trellouser
      - POSTGRES_PASSWORD=trellouser
      - POSTGRES_DB=trello_dev

volumes:
  postgres_data: null
